#pragma once
#include <cuda_runtime.h>
#include <Core/Graphics/Cuda/Memory/DeviceBuffer1DView.hpp>
#include <Core/Graphics/Cuda/Memory/DeviceBuffer2DView.hpp>
#include <Core/Graphics/Cuda/PathTracing/DeviceCamera.hpp>
#include <Core/Graphics/Cuda/PathTracing/PathPoolView.hpp>
#include <Core/Graphics/Cuda/Memory/DeviceQueueView.hpp>
#include <Core/Graphics/Cuda/Bvh/DeviceBvhView.hpp>
#include <Core/Graphics/Cuda/PathTracing/Material.hpp>
#include <Core/Graphics/Cuda/PathTracing/MaterialQueueViews.hpp>

namespace Core::Graphics::Cuda::Kernels
{
	void Clear(uchar4 color, Memory::DeviceBuffer1DView<uchar4> framebuffer);
	void InitializePaths(
		uint32_t generateCount,
		DeviceCamera camera, 
		uint32_t width, 
		uint32_t height, 
		uint32_t sampleGridSize, 
		PathPoolView pathPool, 
		Memory::DeviceQueueView<uint32_t> rayQueue);
	void PrepareIteration(
		Memory::DeviceQueueView<uint32_t> currentRayQueue,
		Memory::DeviceQueueView<uint32_t> nextRayQueue,
		Memory::DeviceQueueView<uint32_t> regenQueue,
		MaterialQueueViews materialQueues,
		uint32_t nextRayCount);
	void IntersectRaysWithScene(
		uint32_t queueSize,
		PathPoolView pathPool, 
		Memory::DeviceQueueView<uint32_t> rayQueue, 
		DeviceBvhView bvh,
		MaterialQueueViews materialQueues,
		Memory::DeviceQueueView<uint32_t> regenQueue);
	void EvaluateNormalMaterial(
		PathPoolView pathPool,
		Memory::DeviceQueueView<HitData> hitQueue,
		Memory::DeviceBuffer1DView<Triangle> triangles,
		Memory::DeviceBuffer1DView<Material> materials,
		uint32_t pathDepthLimit,
		Memory::DeviceQueueView<uint32_t> regenQueue,
		Memory::DeviceBuffer1DView<float4> accumulationBuffer,
		Memory::DeviceQueueView<uint32_t> nextRayQueue);
	void EvaluateDiffuseMaterial(
		PathPoolView pathPool,
		Memory::DeviceQueueView<HitData> hitQueue,
		Memory::DeviceBuffer1DView<Triangle> triangles,
		Memory::DeviceBuffer1DView<Material> materials,
		uint32_t pathDepthLimit,
		Memory::DeviceQueueView<uint32_t> regenQueue,
		Memory::DeviceBuffer1DView<float4> accumulationBuffer,
		Memory::DeviceQueueView<uint32_t> nextRayQueue);
	void EvaluatePhongMaterial(
		PathPoolView pathPool,
		Memory::DeviceQueueView<HitData> hitQueue,
		Memory::DeviceBuffer1DView<Triangle> triangles,
		Memory::DeviceBuffer1DView<Material> materials,
		uint32_t pathDepthLimit,
		Memory::DeviceQueueView<uint32_t> regenQueue,
		Memory::DeviceBuffer1DView<float4> accumulationBuffer,
		Memory::DeviceQueueView<uint32_t> nextRayQueue);
	void EvaluateMirrorMaterial(
		PathPoolView pathPool,
		Memory::DeviceQueueView<HitData> hitQueue,
		Memory::DeviceBuffer1DView<Triangle> triangles,
		Memory::DeviceBuffer1DView<Material> materials,
		uint32_t pathDepthLimit,
		Memory::DeviceQueueView<uint32_t> regenQueue,
		Memory::DeviceBuffer1DView<float4> accumulationBuffer,
		Memory::DeviceQueueView<uint32_t> nextRayQueue);
	void EvaluateGgxMaterial(
		PathPoolView pathPool,
		Memory::DeviceQueueView<HitData> hitQueue,
		Memory::DeviceBuffer1DView<Triangle> triangles,
		Memory::DeviceBuffer1DView<Material> materials,
		uint32_t pathDepthLimit,
		Memory::DeviceQueueView<uint32_t> regenQueue,
		Memory::DeviceBuffer1DView<float4> accumulationBuffer,
		Memory::DeviceQueueView<uint32_t> nextRayQueue);
	void EvaluateEmissiveMaterial(
		PathPoolView pathPool,
		Memory::DeviceQueueView<HitData> hitQueue,
		Memory::DeviceBuffer1DView<Triangle> triangles,
		Memory::DeviceBuffer1DView<Material> materials,
		uint32_t pathDepthLimit,
		Memory::DeviceQueueView<uint32_t> regenQueue,
		Memory::DeviceBuffer1DView<float4> accumulationBuffer,
		Memory::DeviceQueueView<uint32_t> nextRayQueue);
	void RegeneratePaths(
		uint32_t remainingCount,
		Memory::DeviceQueueView<uint32_t> regenQueue,
		uint64_t launchedSampleCount,
		DeviceCamera camera, 
		uint32_t width, 
		uint32_t height, 
		uint32_t sampleGridSize, 
		PathPoolView pathPool,
		Memory::DeviceQueueView<uint32_t> nextRayQueue);
	void PostprocessAccumulatedRadiance(
		Memory::DeviceBuffer1DView<float4> accumulationBuffer,
		float invSpp,
		Memory::DeviceBuffer1DView<uchar4> framebuffer);
}